app = "narf"
primary_region = "den"

[build]

[[mounts]]
  source = "db"
  destination = "/app/db"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

