app = "narf"
primary_region = "den"

[build]

[mounts]
destination = "/app/db"
source = "db"

[http_service]
auto_start_machines = true
auto_stop_machines = "stop"
force_https = true
internal_port = 3000
min_machines_running = 1
processes = ["app"]

[[http_service.checks]]
grace_period = "30s"
interval = "15s"
method = "get"
path = "/"
port = 3000
timeout = "10s"
type = "http"

[[vm]]
memory = 512
