name: Checks

on:
  pull_request:
    branches: [master]

  push:
    branches: [master]

  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.branch }}

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
          cache: npm

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: ESLint
        run: npx eslint .

  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
          cache: npm

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Prettier
        run: npx prettier -c -u .
