name: Checks

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]

  push:
    branches: [main]

  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.branch }}

jobs:
  docker:
    name: Build docker image
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:3
        ports: [5000:5000]
    steps:
      - uses: haliphax/narf/.github/@main

      - uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - uses: docker/build-push-action@v6
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: localhost:5000/narf:latest

  e2e:
    name: End-to-end tests
    runs-on: ubuntu-latest
    steps:
      - uses: haliphax/narf/.github@main

      - name: Cypress
        env:
          host: 0.0.0.0
          TERM: xterm-256color
        run: |
          mkdir db
          npm run build
          npm start &>/dev/null &
          sleep 3
          npm run e2e

  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: haliphax/narf/.github@main

      - name: ESLint
        run: npx eslint .

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: haliphax/narf/.github@main

      - name: Prettier
        run: npx prettier -lu .

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: haliphax/narf/.github@main

      - uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{ github.repository_owner }}

      - name: Run unit tests
        run: npm run coverage

      - name: Add step summary
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          comment-on: none

      - name: Upload coverage report or add comment
        uses: coverallsapp/github-action@v2
        if: always()
        with:
          file: coverage/clover.xml

      - name: Push result to Testspace server
        run: testspace ./coverage/clover.xml ./coverage/junit.xml
        if: always()
