name: Checks

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]

  push:
    branches: [main]

  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.branch }}

jobs:
  build:
    name: Build client
    runs-on: ubuntu-latest
    steps:
      - uses: haliphax/narf/.github@main

      - name: Build client
        run: npm run build

  e2e:
    name: End-to-end tests
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:3
        ports:
          - 5000:5000
    steps:
      - uses: haliphax/narf/.github@main
        with:
          dependencies: "false"

      - name: Set up buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Build
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: localhost:5000/narf:latest

      - name: Start server container
        run: |
          mkdir db
          docker run --rm -d -p 3000:3000 -v $(pwd)/db:/app/db localhost:5000/narf:latest

      - uses: cypress-io/github-action@v6
        with:
          working-directory: .

  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: haliphax/narf/.github@main

      - name: ESLint
        run: npx eslint .

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: haliphax/narf/.github@main

      - name: Prettier
        run: npx prettier -lu .

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: haliphax/narf/.github@main

      - uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{ github.repository_owner }}

      - name: Run unit tests
        run: npm run coverage

      - name: Add step summary
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          comment-on: none

      - name: Upload coverage report or add comment
        uses: coverallsapp/github-action@v2
        if: always()
        with:
          file: coverage/clover.xml

      - name: Push result to Testspace server
        run: testspace ./coverage/clover.xml ./coverage/junit.xml
        if: always()
