name: Checks

on:
  pull_request:
    branches: [main]

  push:
    branches: [main]

  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.branch }}

jobs:
  build:
    name: Build client
    runs-on: ubuntu-latest
    steps:
      - uses: haliphax/narf/.github@main

      - name: Build client
        run: npm run build

  commitlint:
    name: CommitLint
    if: ${{ contains(github.event_name, 'pull_request') }}
    runs-on: ubuntu-latest
    steps:
      - uses: haliphax/narf/.github@main

      - name: Lint pull request title
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: echo "$PR_TITLE" | npx commitlint

  e2e:
    name: End-to-end tests
    runs-on: ubuntu-latest
    steps:
      - uses: haliphax/narf/.github@main
        with:
          dependencies: "false"

      - uses: docker/setup-buildx-action@v3

      - uses: docker/build-push-action@v6
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true
          tags: narf:latest

      - name: Cypress
        env:
          TERM: xterm-256color
        run: |
          mkdir db
          docker run -d -p 3000:3000 -v $(pwd)/db:/app/db narf:latest
          npm i cypress
          npm run e2e

  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: haliphax/narf/.github@main

      - name: ESLint
        run: npx eslint .

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: haliphax/narf/.github@main

      - name: Prettier
        run: npx prettier -l -u .

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: haliphax/narf/.github@main

      - uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{ github.repository_owner }}

      - name: Run unit tests
        run: npm run coverage

      - name: Upload coverage report or add comment
        uses: coverallsapp/github-action@v2
        if: always()
        with:
          file: coverage/clover.xml

      - name: Push result to Testspace server
        run: testspace ./coverage/clover.xml ./coverage/junit.xml
        if: always()
