name: CommitLint

on:
  pull_request:
    branches: [main]
    types: [opened, edited, reopened, synchronize]

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.branch }}

jobs:
  commitlint:
    name: CommitLint
    runs-on: ubuntu-latest
    steps:
      - uses: haliphax/narf/.github@main

      - name: Lint pull request title
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: echo "$PR_TITLE" | npx commitlint
