name: Coverage

on:
  push:
    branches: [main]

jobs:
  coverage:
    name: Coverage report
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Run unit tests with coverage report
        run: npm run coverage -- --reporter lcov

      - name: Upload coverage report
        uses: coverallsapp/github-action@v2
