name: Deploy

on:
  release:
    types: [prereleased, released]

  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}

jobs:
  deploy:
    environment:
      name: fly.io
      url: https://narf.poker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Remove test code
        run: |
          find src -type f -name '*.test.ts' -delete
          rm vitest.config.ts

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
