name: Deploy to Glitch

on:
  release:
    types: [prereleased, released]

  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}

jobs:
  glitch:
    environment:
      name: glitch
      url: https://sphenoid-secret-antimony.glitch.me
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Build application
        env:
          NODE_ENV: production
        run: npm run build && npm run clean

      - name: Trim package.json for production
        run: |
          cat >_package.json <<EOF
          {
            "name": $(jq '.name' <package.json),
            "version": $(jq '.version' <package.json),
            "dependencies": $(jq '.dependencies' <package.json),
            "engines": $(jq '.engines' <package.json),
            "scripts": {
              "start": $(jq '.scripts.start' <package.json)
            }
          }
          EOF
          jq -r >package.json <_package.json
          cat package.json

      - name: Prune node_modules
        run: npm prune --omit=dev

      - name: Push to glitch branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b glitch
          git add dist/ node_modules/ package.json -f
          git commit -m "🚀 deploy to glitch"
          git push -f -u origin glitch
