name: Publish site

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: 18.x
        cache: npm

    - name: Install dependencies
      run: npm i

    - name: Build
      run: |
        #--- build site with Parcel
        npx parcel build --dist-dir docs --public-url /narf \
          src/front-end/index.html

    - name: Publish
      run: |
        #--- publish to GitHub Pages
        git config user.email git@github.com
        git config user.name 'GitHub Actions'
        git add docs
        git commit -m '🚀 publish site'
        git push -f -u origin master:gh-pages
