name: Release new version

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: haliphax/narf/.github@main
        with:
          token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}

      - name: semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
          HUSKY: "0"
        run: npx semantic-release -r git@github.com:haliphax/narf.git
