name: Tests

on:
  pull_request:
    branches: [main]

  push:
    branches: [main]

  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.branch }}

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: haliphax/narf/.github@main

      - name: Run unit tests
        run: npm run coverage

      - name: Upload coverage report or add comment
        uses: coverallsapp/github-action@v2
